# Generated by Django 5.0.3 on 2024-05-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='study.poste')),
                ('destination', models.CharField(max_length=100)),
                ('point_depart', models.CharField(max_length=100)),
                ('heure_depart', models.TimeField()),
                ('nb_places', models.IntegerField()),
                ('contactinfo', models.CharField(default='+216', max_length=100)),
                ('tranport_type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')], default=1)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('study.poste',),
        ),
    ]
