# Generated by Django 5.0.3 on 2024-05-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='study.poste')),
                ('localisation', models.CharField(max_length=100)),
                ('contactinfo', models.CharField(default='+216 xx xxx xxx', max_length=100)),
                ('logement_type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')], default=1)),
            ],
            bases=('study.poste',),
        ),
    ]
